version: '3.7'

services:

  mongo:
    image: mongo:7.0.5
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ytheTY
    ports:
      - 27017:27017
    volumes:
      - './mongodb/mongodb_data:/data/db'
      - './mongodb/mongodb_config:/data/configdb'

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ytheTY
      ME_CONFIG_MONGODB_URL: mongodb://root:ytheTY@mongo:27017/
    depends_on:
      - mongo
